# Open Notebook airgap — generate an auto-configured app\.env (run by 2-airgap-install.bat).
# - random encryption key
# - OLLAMA_BASE_URL from -OllamaHost (default 127.0.0.1 = Ollama on this PC)
# - CORS_ORIGINS auto-filled with localhost / 127.0.0.1 / detected LAN IP (port 8502)
# Leaves an existing .env untouched (install is run-once; key must stay stable).
param(
  [Parameter(Mandatory = $true)][string]$AppDir,
  [string]$OllamaHost = "127.0.0.1"
)
$ErrorActionPreference = 'Stop'

$envPath = Join-Path $AppDir '.env'
if (Test-Path $envPath) {
  Write-Output "[env] $envPath already exists - leaving untouched"
  exit 0
}

$lan = (& (Join-Path $PSScriptRoot 'detect_lan_ip.ps1'))
$key = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 40 | ForEach-Object { [char]$_ })
$cors = "http://localhost:8502,http://127.0.0.1:8502"
if ($lan) { $cors += ",http://$($lan):8502" }

$content = @"
# Open Notebook - air-gapped config (auto-generated by 2-airgap-install.bat)
OPEN_NOTEBOOK_ENCRYPTION_KEY=$key

# Database (native Windows MUST use 127.0.0.1, not localhost)
SURREAL_URL=ws://127.0.0.1:8000/rpc
SURREAL_USER=root
SURREAL_PASSWORD=root
SURREAL_NAMESPACE=open_notebook
SURREAL_DATABASE=open_notebook
# API
# 3-run.bat may override API_HOST/CORS_ORIGINS per run for --local/--allow-host.
# Default install is LAN-capable; use 3-run.bat --local for loopback-only operation.
API_HOST=0.0.0.0
API_PORT=5055
API_RELOAD=false

# On-prem Ollama endpoint. Same PC = 127.0.0.1 (works with default Ollama binding).
# For an Ollama on another PC: 2-airgap-install.bat --ollama-host <ip>  (that PC's Ollama must bind 0.0.0.0).
OLLAMA_BASE_URL=http://$($OllamaHost):11434

# Browser origins allowed to call the API. credentials=True is incompatible with '*',
# so explicit origins are required (auto-filled with this PC's hosts on port 8502).
CORS_ORIGINS=$cors
"@

Set-Content -Path $envPath -Value $content -Encoding ascii
Write-Output "[env] wrote $envPath (ollama=$($OllamaHost):11434, cors=$cors)"
